services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: 
      context: .
      dockerfile: ./packages/backend/dockerfile
    labels:
      caddy: "${APP_FQDN}"
      caddy.handle: /api/*
      caddy.handle.reverse_proxy: "{{upstreams 3000}}"

  frontend:
    build: 
      context: .
      dockerfile: ./packages/frontend/dockerfile
    labels:
      caddy: "${APP_FQDN}"
      # caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 5173}}"

volumes:
  caddy-data:
  caddy-config: