services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "3000:3000"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: 
      context: .
      dockerfile: ./packages/backend/dockerfile
    labels:
      caddy: "${APP_FQDN}"
      caddy.handle: /api/*
      caddy.handle.reverse_proxy: "{{upstreams 3000}}"
    develop:
      watch: 
        - action: rebuild
        - path: ./packages/backend

  frontend:
    build: 
      context: .
      dockerfile: ./packages/frontend/develop.dockerfile
    labels:
      caddy: "${APP_FQDN}"
      # caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 5173}}"
    develop: 
      watch: 
        - action: sync
          path: ./packages/frontend
          target: /app/packages/frontend


volumes:
  caddy-data:
  caddy-config:
  timescaledb-data: